const express = require('express')
const app = express()
const mongoose = require('mongoose')
const addProductRouter = require('./routers/addProduct')
const seeProducts = require("./routers/seeProduct")
const viewProducts = require("./routers/viewProduct")
const deleteproduct = require("./routers/deleteProduct")
const heroproduct = require('./routers/heroproduct')
const atlasproduct = require('./routers/atlasproduct')
const herculesproduct = require('./routers/Herculesproduct')
const updateproduct = require('./routers/updateproduct')
const signuprouter = require('./routers/signup')
const loginrouter = require('./routers/login')
const userdata = require("./routers/userdata")
const kidsrouter = require("./routers/kids")
const mensrouter = require("./routers/Men")
const editprofile = require("./routers/editprofile")
const cartrouter = require('./routers/cartproduct')
const order = require("./routers/orderdetails")
const count = require("./routers/total")
const admin = require("./routers/adminlogin")
const chatpanel = require("./routers/message")
const cors = require('cors')

require('dotenv').config()
const PORT = process.env.PORT || 5000

mongoose.connect(process.env.MONGO_URI).then(()=>{
    console.log("mongoDb Connected")
}).catch((err)=>{
    console.log(err)
})

app.use(express.json())
app.use(cors())
app.use(express.static("public"))


app.use(addProductRouter)
app.use(seeProducts)
app.use(viewProducts)
app.use(deleteproduct)
app.use(heroproduct)
app.use(atlasproduct)
app.use(herculesproduct)
app.use(signuprouter)
app.use(updateproduct)
app.use(count)
app.use(loginrouter)
app.use(userdata)
app.use(kidsrouter)
app.use(mensrouter)
app.use(editprofile)
app.use(order)
app.use(cartrouter)
app.use(admin)
app.use(chatpanel)
// app.use(cartproduct)


app.listen(PORT,()=>console.log("Server is Running"))